### ISSUE TITLE
Add ability to activate with fingers

### ISSUE THREAD

**Issue by N10A100** [Edward7s/Nocturnal-CVR-Player-List#1]
I really like the extra immersion, but I wish I could brush things with my fingers. Perhaps the vibration intensity could even be lower when you touch with your fingers and then get stronger when you touch with more of your hand?
I don't know the proper etiquette for GitHub feature requests so I'll just say please and thank you!

**Comment by xoxovrc** [comment]
Hi, I am not sure sure what do u mean by that, if u would want me to do like a kinda button for each user to open a menu it should not be hard tho the only issue with this game its that the ui does not get triggered by the game itself cause they have a weird type of mesh rendered html menu, and i've tryied few stuff like a colider behaind it and stuff like that but sadly that didn't work out, so I would probably need to do a new raycast to trigger my ui, tho im not in the country for few days and also I want do finish some other projects before I would do something like this.
